repo_name: Cntrl Alt Del
repo_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_ctrl_alt_del
site_name: Cntrl Alt Del
site_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_ctrl_alt_del
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
  language: pt-BR

extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Participantes: participantes/participantes.md
  - Canvas: Canvas/Canvas.md
  - Modelo:
    - Modelo de ML: Modelo/modelo.md
    - Coleta de dados: Dados/dados.md