name: Deploy Backend

on:
  push:
    branches:
      - feat/cd-ci-aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/challenge_1_ctrl_alt_del
            git pull origin main
            docker compose up -d --build backend